### ISSUE TITLE
input for argNorm for ARGs-OAP

### ISSUE THREAD

**Issue by ellyyuyang** [BigDataBiology/argNorm#7]
Hi Developers!

Thanks for this amazing effort in standardization! I learned about this work in your talk in EMBARK!

My question is the input for argNorm for ARGs-OAP outputs. ARGs-OAP has a bunch of output files in different units (normalized and unnormalized) and in different ontology levels (gene, subtype, type) generated from stagetwo. Which one shall I use for inputting to argNorm?

Also, I am wondering if the ARGs-OAP section updated to the newest ARGs-OAP version, which is version 3.0 (https://github.com/xinehc/args_oap)? 

Thanks!
Yu

**Comment by SvetlanaUP** [comment]
Thanks for your feedback, Yu! We will update the documentation with tool/database versions. 

As input, the argNorm can use "raw" and hAMRonized outputs (https://github.com/BigDataBiology/argNorm/tree/main/outputs) from ORF (args_oap_hmm_result.tsv) and read (stage2output.normalize_cellnumber.gene.txt & args_oap_reads_result.tsv) running mode.

Our ARGs-OAP run is documented here https://github.com/BigDataBiology/arg-compare/tree/master/ARGs-OAP where you can find how we hAMRonized the ARGs-OAP outputs.

As for the tool version, we used ARGs-OAP v2.3.
